name: Github Action testing
on: 
	push:
		branches:
			- main
jobs:
	build-and-deploy:
		runs-on: ubuntu-latest
		steps:
			- name: Checkout
				uses: actions/checkout@v2

			- name: Build and Deploy
				uses: JamesIves/github-pages-deploy-action@master
				env:
					ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
					BRANCH: gh-pages
					FOLDER: dist
					BUILD_SCRIPT: npm install && npm run build