name: Github Action testing
on:
  push:
    branches:
      - main
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

			-name: Install and Build
				run: |
					npm ci
					npm run build

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: .